image: python:3.9.13

test-evalhyd-python:
  stage: test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    # print Python version
    - python --version
    # compile and install package
    - python -m pip install --user .
    # make sure package can be imported and check version
    - python -c "import evalhyd;print(evalhyd.__version__)"
    # run test suite
    - (cd ./tests && python run_all_tests.py)
