image: python:latest

build-job:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    # print Python version
    - python --version
    # set up virtual environment
    - pip install virtualenv
    # compile and install library
    - pip install -e .

test-job:
  stage: test
  script:
    # run test suite
    - (cd ./tests && python run_all_tests.py)
