name: evalhyd-python-env
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cxx-compiler
  - c-compiler
  - cmake
  - make
  - scikit-build
  # Host dependencies
  - python
  - numpy
  - pybind11
  - xtensor-python==0.26.1
#TODO:  - evalhyd==0.0.1
  # Test dependencies
  - numpy
