channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cxx-compiler
  - c-compiler
  - cmake
  - make
  - scikit-build
  # Host dependencies
  - python
  - numpy
  - pybind11
  - xtl==0.8.0
  - xtensor==0.26.0
  - xtensor-python==0.28.0
#  - evalhyd-cpp==0.1.0
  # Test dependencies
  - numpy
